=== opentech-ux/lom-compiler/schemas/lom.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://example.com/schema/lom.schema.json",
    "type": "object",
    "title": "LOM",
    "description": "Specification of the wireframe of a single Web page",
    "additionalProperties": true,
    "properties": {
        "rootPath": {
            "$ref": "#/$defs/Path"
        },
        "pageWidth": {
            "$ref": "#/$defs/Dimension"
        },
        "pageHeight": {
            "$ref": "#/$defs/Dimension"
        },
        "loms": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "/?([a-zA-Z0-9._-]+)(/[a-zA-Z0-9._-]+)*": {
                    "$ref": "#/$defs/Zone"
                }
            }
        }
    },
    "required": [
        "rootPath",
        "pageWidth",
        "pageHeight",
        "loms"
    ],
    "$defs": {
        "Dimension": {
            "type": "number",
            "description": "Size of a graphical element along an axis",
            "minimum": 0
        },
        "Path": {
            "type": "string",
            "description": "A slash separated path",
            "pattern": "/?([a-zA-Z0-9._-]+)(/[a-zA-Z0-9._-]+)*"
        },
        "Bounds": {
            "type": "object",
            "description": "Coordinates of an axis-aligned rectangle",
            "additionalProperties": false,
            "properties": {
                "x": {
                    "type": "number",
                    "description": "x coordinate relative to parent zone"
                },
                "y": {
                    "type": "number",
                    "description": "y coordinate relative to parent zone"
                },
                "width": {
                    "$ref": "#/$defs/Dimension"
                },
                "height": {
                    "$ref": "#/$defs/Dimension"
                }
            },
            "required": [
                "x",
                "width",
                "height",
                "y"
            ]
        },
        "Zone": {
            "type": "object",
            "description": "Representation of a zone on screen",
            "properties": {
                "zoneId": {
                    "type": "string",
                    "description": "Unique ID of this zone"
                },
                "bounds": {
                    "$ref": "#/$defs/Bounds"
                },
                "children": {
                    "type": "array",
                    "description": "List of children zones of this zone",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/$defs/Zone"
                    }
                },
                "link": {
                    "$ref": "#/$defs/Path"
                },
                "style": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "background": {
                            "type": "string"
                        },
                        "border": {
                            "type": "string"
                        }
                    }
                }
            },
            "required": [
                "bounds"
            ]
        }
    }
}

=== opentech-ux/lom-compiler/tests/resources/multi-lom/basic.lom.json
{
  "loms": {
    "": {
      "bounds": {
        "height": 600,
        "width": 800,
        "x": 100,
        "y": 100
      },
      "children": [
        {
          "bounds": {
            "height": 20,
            "width": 300,
            "x": 150,
            "y": 10
          },
          "link": "otherPage",
          "style": {
            "background": "#90ff90",
            "border": "2px solid red"
          }
        },
        {
          "bounds": {
            "height": 20,
            "width": 300,
            "x": 150,
            "y": 200
          },
          "link": "/",
          "style": {
            "background": "#bbbbbb",
            "border": "2px dashed blue"
          }
        }
      ],
      "zoneId": "rootZone"
    },
    "otherPage": {
      "bounds": {
        "height": 200,
        "width": 200,
        "x": 50,
        "y": 50
      },
      "children": [
        {
          "bounds": {
            "height": 50,
            "width": 50,
            "x": 20,
            "y": 20
          },
          "link": "/"
        }
      ],
      "style": {
        "background": "yellow",
        "border": "none"
      }
    }
  },
  "pageHeight": 1080,
  "pageWidth": 1920,
  "rootPath": "/"
}

=== opentech-ux/lom-compiler/tests/resources/basic-lom/basic.lom.json
{
  "rootPath": "/",
  "pageWidth": 1920,
  "pageHeight": 1080,
  "loms": {
    "": {
      "zoneId": "rootZone",
      "bounds": {
        "x": 100,
        "y": 100,
        "width": 800,
        "height": 600
      },
      "children": [
        {
          "bounds": {
            "x": 150,
            "y": 10,
            "width": 300,
            "height": 20
          },
          "link": "otherPage",
          "style": {
            "background": "#90ff90",
            "border": "2px solid red"
          }
        },
        {
          "bounds": {
            "x": 150,
            "y": 200,
            "width": 300,
            "height": 20
          },
          "link": "/",
          "style": {
            "background": "#bbbbbb",
            "border": "2px dashed blue"
          }
        }
      ]
    },
    "otherPage": {
      "bounds": {
        "x": 50,
        "y": 50,
        "width": 200,
        "height": 200
      },
      "style": {
        "background": "yellow",
        "border": "none"
      },
      "children": [
        {
          "bounds": {
            "x": 20,
            "y": 20,
            "width": 50,
            "height": 50
          },
          "link": "/"
        }
      ]
    }
  }
}
